<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260411063947 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE orders (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number VARCHAR(255) NOT NULL, total NUMERIC(14, 4) NOT NULL, customer_name TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, shop_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E52FFDEE4D16C4DD ON orders (shop_id)');
        $this->addSql('CREATE TABLE shops (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE telegram_integrations (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, bot_token TEXT NOT NULL, chat_id TEXT NOT NULL, enabled BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, shop_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_15982CDC4D16C4DD ON telegram_integrations (shop_id)');
        $this->addSql('CREATE TABLE telegram_send_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message TEXT NOT NULL, status VARCHAR(255) NOT NULL, error TEXT DEFAULT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, shop_id INT NOT NULL, order_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_77AA2A944D16C4DD ON telegram_send_log (shop_id)');
        $this->addSql('CREATE INDEX IDX_77AA2A948D9F6D38 ON telegram_send_log (order_id)');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEE4D16C4DD FOREIGN KEY (shop_id) REFERENCES shops (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE telegram_integrations ADD CONSTRAINT FK_15982CDC4D16C4DD FOREIGN KEY (shop_id) REFERENCES shops (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE telegram_send_log ADD CONSTRAINT FK_77AA2A944D16C4DD FOREIGN KEY (shop_id) REFERENCES shops (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE telegram_send_log ADD CONSTRAINT FK_77AA2A948D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE orders DROP CONSTRAINT FK_E52FFDEE4D16C4DD');
        $this->addSql('ALTER TABLE telegram_integrations DROP CONSTRAINT FK_15982CDC4D16C4DD');
        $this->addSql('ALTER TABLE telegram_send_log DROP CONSTRAINT FK_77AA2A944D16C4DD');
        $this->addSql('ALTER TABLE telegram_send_log DROP CONSTRAINT FK_77AA2A948D9F6D38');
        $this->addSql('DROP TABLE orders');
        $this->addSql('DROP TABLE shops');
        $this->addSql('DROP TABLE telegram_integrations');
        $this->addSql('DROP TABLE telegram_send_log');
    }
}
